package models.modules;

import java.time.LocalDateTime;
import java.util.Properties;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import models.helpers.DateHelper;
import models.helpers.PopupDialog;
import models.schemas.User;

public class Emailer {
    private static final String HOST = "smtp.gmail.com";
    private static final String PORT = "587";

    // Email
    private static final String FROM = "zavskitchenandrestobar.pms@gmail.com";
    // Password
    private static final String APP_PASSWORD = "jgzh sznn oxap ypig";

    // Returns Properties that will be used to send email
    private static Properties getProps() {
        // Configuring
        Properties props = System.getProperties();
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.ssl.trust", HOST);
        props.put("mail.smtp.host", HOST);
        props.put("mail.smtp.user", FROM);
        props.put("mail.smtp.password", APP_PASSWORD);
        props.put("mail.smtp.port", PORT);
        props.put("mail.smtp.auth", "true");

        return props;
    }

    // Sends OTP to user
    public static boolean sendOTP(String receiver, String OTP) {
        Session session = Session.getDefaultInstance(getProps());
        MimeMessage message = new MimeMessage(session);

        try {
            message.setFrom(new InternetAddress(FROM));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(receiver));
            message.setSubject("Login OTP Code");
            message.setText("Login attempt during " + DateHelper.getCurrentDateTimeString() + " at "
                    + Security.getSystemName() + ".\n\n\n Your OTP Code is: " + OTP
                    + "\n\n this password will expire in the next 5 minutes.");
            Transport transport = session.getTransport("smtp");
            transport.connect(HOST, FROM, APP_PASSWORD);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
            return true;
        } catch (Exception e) {
            PopupDialog.showErrorDialog(e, "models.modules.Emailer");
            return false;
        }
    }

    public static boolean sendReport(String receiver, String reportTypeString, User loggedInUser,
            String reportFilePath) {
        Session session = Session.getDefaultInstance(getProps());
        MimeMessage message = new MimeMessage(session);

        try {
            message.setFrom(new InternetAddress(FROM));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(receiver));
            message.setSubject(reportTypeString + " : " + LocalDateTime.now());

            BodyPart messageBodyPart = new MimeBodyPart();
            messageBodyPart.setText("Attached in this message is a " + reportTypeString
                    + ". This is an automatically generated e-mail generated at " + Security.getSystemName()
                    + ", generated by \"" + loggedInUser.getUname() + "\" on " + DateHelper.getCurrentDateTimeString());

            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(messageBodyPart);

            messageBodyPart = new MimeBodyPart();
            DataSource source = new FileDataSource(reportFilePath);
            messageBodyPart.setDataHandler(new DataHandler(source));
            messageBodyPart.setFileName(reportFilePath);
            multipart.addBodyPart(messageBodyPart);

            message.setContent(multipart);

            Transport transport = session.getTransport("smtp");
            transport.connect(HOST, FROM, APP_PASSWORD);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
            return true;
        } catch (Exception e) {
            PopupDialog.showErrorDialog(e, "models.modules.Emailer");
        }
        return false;
    }
}
